package licef.tsapi.vocabulary;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from 22-rdf-syntax-ns.rdf 
 * @author Auto-generated by schemagen on 26 nov. 2013 15:45 
 */
public class RDF {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The first item in the subject RDF list.</p> */
    public static final ObjectProperty first = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" );
    
    /** <p>The object of the subject RDF statement.</p> */
    public static final ObjectProperty object = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#object" );
    
    /** <p>The predicate of the subject RDF statement.</p> */
    public static final ObjectProperty predicate = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate" );
    
    /** <p>The rest of the subject RDF list after the first item.</p> */
    public static final ObjectProperty rest = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest" );
    
    /** <p>The subject of the subject RDF statement.</p> */
    public static final ObjectProperty subject = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject" );
    
    /** <p>The subject is an instance of a class.</p> */
    public static final ObjectProperty type = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" );
    
    /** <p>Idiomatic property used for structured values.</p> */
    public static final ObjectProperty value = m_model.createObjectProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#value" );
    
    /** <p>The class of containers of alternatives.</p> */
    public static final OntClass Alt = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt" );
    
    /** <p>The class of unordered containers.</p> */
    public static final OntClass Bag = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag" );
    
    /** <p>The class of RDF Lists.</p> */
    public static final OntClass List = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#List" );
    
    /** <p>The class of RDF properties.</p> */
    public static final OntClass Property = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property" );
    
    /** <p>The class of ordered containers.</p> */
    public static final OntClass Seq = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq" );
    
    /** <p>The class of RDF statements.</p> */
    public static final OntClass Statement = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement" );
    
}
