package licef.tsapi.vocabulary;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from rdfs.rdf 
 * @author Auto-generated by schemagen on 22 nov. 2013 09:46 
 */
public class RDFS extends VocabularyModel {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    static {
        m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);
    }
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2000/01/rdf-schema#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A description of the subject resource.</p> */
    public static final OntProperty comment = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#comment" );
    
    /** <p>A domain of the subject property.</p> */
    public static final OntProperty domain = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#domain" );
    
    /** <p>The defininition of the subject resource.</p> */
    public static final OntProperty isDefinedBy = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#isDefinedBy" );
    
    /** <p>A human-readable name for the subject.</p> */
    public static final OntProperty label = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#label" );
    
    /** <p>A member of the subject resource.</p> */
    public static final OntProperty member = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#member" );
    
    /** <p>A range of the subject property.</p> */
    public static final OntProperty range = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#range" );
    
    /** <p>Further information about the subject resource.</p> */
    public static final OntProperty seeAlso = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#seeAlso" );
    
    /** <p>The subject is a subclass of a class.</p> */
    public static final OntProperty subClassOf = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#subClassOf" );
    
    /** <p>The subject is a subproperty of a property.</p> */
    public static final OntProperty subPropertyOf = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#subPropertyOf" );
    
}
